name: Run CI
on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    environment:
      name: testing
    env:
      BASE_PATH: ${{vars.BASE_PATH}}
      CLOUDINARY_CLOUD_NAME: ${{vars.CLOUDINARY_CLOUD_NAME}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: pnpm install
        run: nix develop -c pnpm install

      - name: run vitest
        run: nix develop -c pnpm vitest
