name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run CI]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Install dependencies
        run: nix develop -c pnpm install

      - name: Build Page
        env:
          BASE_PATH: ${{vars.BASE_PATH}}
          CLOUDINARY_CLOUD_NAME: ${{vars.CLOUDINARY_CLOUD_NAME}}
        run: nix develop -c pnpm build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
